name: tag-release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and release the tagged version
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      release-command: yarn release
      type: latest

  # Deployment steps taken from https://github.com/colinwilson/static-site-to-vercel/blob/master/.github/workflows/deploy-preview.yml
  repl_build:
    name: Build REPL
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 20
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - name: Install wasm-opt
        run: |
          curl -L -O https://github.com/WebAssembly/binaryen/releases/download/version_116/binaryen-version_116-x86_64-linux.tar.gz
          tar -xf binaryen-version_116-x86_64-linux.tar.gz
          echo "$PWD/binaryen-version_116/bin" >> $GITHUB_PATH
      - uses: Swatinem/rust-cache@v2
        with:
          key: wasm
      - name: Bump max inotify watches
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p;
      - run: yarn --frozen-lockfile
      - name: Build native packages
        run: yarn build-native-release
      - run: yarn build
      - run: yarn build-native-wasm
      - run: yarn workspace @parcel/repl build
      # - name: Upload REPL
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: REPL
      #     path: 'packages/dev/repl/dist'
      - name: Start Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          env: Production
          override: false
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        id: vercel-action
        with:
          vercel-token: ${{ secrets.REPL_VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.REPL_VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.REPL_VERCEL_PROJECT_ID }}
          github-comment: false
          working-directory: packages/dev/repl
          vercel-args: '--prod'
      - name: Update Deployment Status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: Production
          override: false
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ steps.vercel-action.outputs.preview-url }}
